name: Development

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore ElevatedTutorsWebsite/ElevatedTutorsWebsite.csproj

      - name: Build project
        run: dotnet build ElevatedTutorsWebsite/ElevatedTutorsWebsite.csproj --configuration Release --no-restore

      - name: Run tests
        run: dotnet test ElevatedTutorsWebsite/ElevatedTutorsWebsite.csproj --no-build --verbosity normal
